//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BK_CT_DATHANG
    {
        public string madathang { get; set; }
        public string masach { get; set; }
        public int soluongdat { get; set; }
        public int dongia { get; set; }
        public int thanhtien { get; set; }
    }
}
