//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        public string masach { get; set; }
        public string mapn { get; set; }
        public int soluong { get; set; }
        public int gianhap { get; set; }
        public int thanhtien { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
