//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DATHANGs = new HashSet<DATHANG>();
            this.HOADONs = new HashSet<HOADON>();
        }

        [Display(Name = "Mã khách hàng")]
        public string makh { get; set; }
        
 
        [Required(ErrorMessage = "Tên khách hàng là bắt buộc!")]
        [RegularExpression("^([^0-9]*)([^%@#$&*])$", ErrorMessage = "Tên khách hàng không hợp lệ!")]
        [Display(Name = "Tên khách hàng")]
        public string tenkh { get; set; }
       
 
        [Required(ErrorMessage = "Địa chỉ là bắt buộc!")]
        [StringLength(100)]
        [Display(Name = "Địa chỉ")]
        public string diachi { get; set; }
        
 
        [Required(ErrorMessage = "Số điện thoại là bắt buộc!")]
        [RegularExpression("^[0-9]{10,11}$", ErrorMessage = "Số điện thoại không hợp lệ!")]
        [Display(Name = "Số điện thoại")]
        
        public string sodienthoai { get; set; }
 
        [Required(ErrorMessage = "Email là bắt buộc!")]
        [StringLength(50, ErrorMessage = "Chiều dài email lớn nhất là 50")]
        [EmailAddress(ErrorMessage = "Vui lòng nhập lại email!")]
        [Display(Name = "Email")]
        public string email { get; set; }
        

        [Required(ErrorMessage = "Mật khẩu là bắt buộc!")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Chiều dài mật khẩu phải lớn hơn 10 và nhỏ hơn 50")]
        [DataType("password")]
        [Display(Name = "Mật khẩu")]
        public string matkhaukh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
