//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CT_DATHANG = new HashSet<CT_DATHANG>();
            this.CT_HOADON = new HashSet<CT_HOADON>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
        }
    
        public string masach { get; set; }
        public string tensach { get; set; }
        public string matheloai { get; set; }
        public int dongiaban { get; set; }
        public int luotmua { get; set; }
        public double khuyenmai { get; set; }
        public string anhbia { get; set; }
        public bool tinhtrang { get; set; }
        public string mota { get; set; }
        public string nhaxuatban { get; set; }
        public string tacgia { get; set; }
        public System.DateTime ngayxuatban { get; set; }
        public int soluongton { get; set; }
        public int delflag { get; set; }
        public Nullable<System.DateTime> timedel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DATHANG> CT_DATHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
